- name: variables from play level
  hosts: localhost
  vars:
    course: "devops"
    trainer: "shivakumar"
    duration: "110hrs"
  tasks:
    - name: check variables
      vars:
        course: "Devops with AWS"
      ansible.builtin.debug:
        msg:  msg: "Hi, iam learning {{course}}, trainer is {{trainer}}, duration is {{duration}}"