- name: variables from play level
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
    - name: check variables
      vars:
        course: "Devops with AWS"
      ansible.builtin.debug:
        msg: "Hi, iam learning {{course}}, trainer is {{trainer}},
         duration is {{duration}}"